name: pulsing_border
description: "A Flutter package for adding a pulsing border around a widget."
version: 1.0.0
repository: https://github.com/LampeMW/pulsing_border

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
